name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric
  # command:
  #   start: export FABRIC_VERSION=1.4.4;export FABRIC_CA_VERSION=1.4.4;docker-compose -f networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml up -d;sleep 10s
  #   end: docker-compose -f networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*

info:
  Version: 2.1.0
  Size: 2 Orgs with 5 Peer
  Orderer: Kafka
  Distribution: Single Host
  StateDB: CouchDB

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem

  client0.org2.example.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/User1@org2.example.com-cert.pem

channels:
  mychannel:
    # configBinary: networks/fabric/base/mychannel.tx
    created: true
    contracts: [{ "id": "fabcar", "version": "1", "language" : "node" }]
    definition:
      capabilities: []
      consortium: "SampleConsortium"
      msps: ["Org1MSP", "Org2MSP"]
      version: 0
    orderers:
      - orderer.example.com
      - orderer2.example.com
      - orderer3.example.com
      
    peers:
      peer0.org1.example.com:
        eventSource: true
      peer0.org2.example.com:
        eventSource: true

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
      - peer2.org1.example.com
      - peer3.org1.example.com
      - peer4.org1.example.com
      - peer5.org1.example.com
      - peer6.org1.example.com
      - peer7.org1.example.com
      - peer8.org1.example.com
      - peer9.org1.example.com
      - peer10.org1.example.com
      - peer11.org1.example.com
      - peer12.org1.example.com
      - peer13.org1.example.com
      - peer14.org1.example.com

    # certificateAuthorities:
    #   - ca.org1.example.com
    adminPrivateKey:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
      - peer1.org2.example.com
      - peer2.org2.example.com
      - peer3.org2.example.com
      - peer4.org2.example.com
      - peer5.org2.example.com
      - peer6.org2.example.com
      - peer7.org2.example.com
      - peer8.org2.example.com
      - peer9.org2.example.com
      - peer10.org2.example.com
      - peer11.org2.example.com
      - peer12.org2.example.com
      - peer13.org2.example.com
      - peer14.org2.example.com
    # certificateAuthorities:
    #   - ca.org2.example.com
    adminPrivateKey:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem

orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
    tlsCACerts:
      path: networks/fabric/base/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  orderer2.example.com:
    url: grpcs://localhost:8050
    grpcOptions:
      ssl-target-name-override: orderer2.example.com
    tlsCACerts:
      path: networks/fabric/base/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  orderer3.example.com:
    url: grpcs://localhost:9050
    grpcOptions:
      ssl-target-name-override: orderer3.example.com
    tlsCACerts:
      path: networks/fabric/base/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer1.org1.example.com:
    url: grpcs://localhost:7056
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer2.org1.example.com:
    url: grpcs://localhost:7061
    grpcOptions:
      ssl-target-name-override: peer2.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer3.org1.example.com:
    url: grpcs://localhost:7066
    grpcOptions:
      ssl-target-name-override: peer3.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem
  
  peer4.org1.example.com:
    url: grpcs://localhost:7071
    grpcOptions:
      ssl-target-name-override: peer4.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer4.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer5.org1.example.com:
    url: grpcs://localhost:7076
    grpcOptions:
      ssl-target-name-override: peer5.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer5.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer6.org1.example.com:
    url: grpcs://localhost:7081
    grpcOptions:
      ssl-target-name-override: peer6.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer6.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer7.org1.example.com:
    url: grpcs://localhost:7086
    grpcOptions:
      ssl-target-name-override: peer7.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer7.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer8.org1.example.com:
    url: grpcs://localhost:7091
    grpcOptions:
      ssl-target-name-override: peer8.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer8.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer9.org1.example.com:
    url: grpcs://localhost:7096
    grpcOptions:
      ssl-target-name-override: peer9.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer9.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer10.org1.example.com:
    url: grpcs://localhost:7101
    grpcOptions:
      ssl-target-name-override: peer10.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer10.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer11.org1.example.com:
    url: grpcs://localhost:7106
    grpcOptions:
      ssl-target-name-override: peer11.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer11.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer12.org1.example.com:
    url: grpcs://localhost:7111
    grpcOptions:
      ssl-target-name-override: peer12.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer12.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer13.org1.example.com:
    url: grpcs://localhost:7116
    grpcOptions:
      ssl-target-name-override: peer13.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer13.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer14.org1.example.com:
    url: grpcs://localhost:7121
    grpcOptions:
      ssl-target-name-override: peer14.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer14.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  # peer15.org1.example.com:
  #   url: grpcs://localhost:7126
  #   grpcOptions:
  #     ssl-target-name-override: peer15.org1.example.com
  #     grpc.keepalive_time_ms: 600000
  #   tlsCACerts:
  #     path: networks/fabric/base/crypto-config/peerOrganizations/org1.example.com/peers/peer15.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer0.org2.example.com:
    url: grpcs://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem
      
  peer1.org2.example.com:
    url: grpcs://localhost:8056
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer2.org2.example.com:
    url: grpcs://localhost:9061
    grpcOptions:
      ssl-target-name-override: peer2.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer2.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer3.org2.example.com:
    url: grpcs://localhost:9066
    grpcOptions:
      ssl-target-name-override: peer3.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer3.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer4.org2.example.com:
    url: grpcs://localhost:9071
    grpcOptions:
      ssl-target-name-override: peer4.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer4.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer5.org2.example.com:
    url: grpcs://localhost:9076
    grpcOptions:
      ssl-target-name-override: peer5.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer5.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer6.org2.example.com:
    url: grpcs://localhost:9081
    grpcOptions:
      ssl-target-name-override: peer6.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer6.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer7.org2.example.com:
    url: grpcs://localhost:9086
    grpcOptions:
      ssl-target-name-override: peer7.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer7.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer8.org2.example.com:
    url: grpcs://localhost:9091
    grpcOptions:
      ssl-target-name-override: peer8.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer8.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer9.org2.example.com:
    url: grpcs://localhost:9096
    grpcOptions:
      ssl-target-name-override: peer9.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer9.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer10.org2.example.com:
    url: grpcs://localhost:9101
    grpcOptions:
      ssl-target-name-override: peer10.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer10.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer11.org2.example.com:
    url: grpcs://localhost:9106
    grpcOptions:
      ssl-target-name-override: peer11.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer11.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer12.org2.example.com:
    url: grpcs://localhost:9111
    grpcOptions:
      ssl-target-name-override: peer12.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer12.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer13.org2.example.com:
    url: grpcs://localhost:9116
    grpcOptions:
      ssl-target-name-override: peer13.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer13.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer14.org2.example.com:
    url: grpcs://localhost:9121
    grpcOptions:
      ssl-target-name-override: peer14.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer14.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  # peer15.org2.example.com:
  #   url: grpcs://localhost:9126
  #   grpcOptions:
  #     ssl-target-name-override: peer15.org2.example.com
  #     grpc.keepalive_time_ms: 600000
  #   tlsCACerts:
  #     path: networks/fabric/base/crypto-config/peerOrganizations/org2.example.com/peers/peer15.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem
